"use client";
import SideBar from "./SideBar";
import styles from "./page.module.css";
import "./globals.css";
import TopBar from "./TopBar";
import { SessionProvider, signIn, useSession } from "next-auth/react";
import DataInitializer from "../../components/dataInitializer";
import { Provider } from "react-redux";
import store from "../../store/store";
export const metadata = {
  title: "aa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ...props
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <SessionProvider session={props.session}>
            <DataInitializer>
              <TopBar></TopBar>
              <div className={styles.right}>
                <SideBar></SideBar>
                <div className={styles.child}> {children}</div>
              </div>
            </DataInitializer>
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
